
apiVersion: apps/v1
kind: Deployment

metadata:
  name: github-argocd-demo

spec:
  replicas: 5

  selector:
    matchLabels:
      app: github-argocd-demo

  template:
    metadata:
      labels:
        app: github-argocd-demo

    spec:
      containers:
        - name: web
          image: mohamedfawzy1/github-argocd-demo:2b6597435e990029af2c3bf11964496d383e1809

          ports:
            - containerPort: 80
