
apiVersion: apps/v1
kind: Deployment

metadata:
  name: github-argocd-demo

spec:
  replicas: 5

  selector:
    matchLabels:
      app: github-argocd-demo

  template:
    metadata:
      labels:
        app: github-argocd-demo

    spec:
      containers:
        - name: web
          image: mohamedfawzy1/github-argocd-demo:46f49ac2a4f8c4f0ba67946059a712c5ddb803aa

          ports:
            - containerPort: 80
